vochain: try not to panic on requests while initializing
If a read-only request comes in while InitChain hasn't happened yet,
we'll panic since immutable trees like IAppTree are still nil.

To try to remediate this, set them to the best initial values we can in
NewState. Add a TODO since, while better than nil, it's still not great.

Add a "does not panic" test too. Just like the report, it would panic
before the fix:

	--- FAIL: TestVochainState (0.08s)
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
		panic: runtime error: invalid memory address or nil pointer dereference
	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x208ffe6]

	goroutine 68 [running]:
	testing.tRunner.func1.1(0x26c1720, 0x3aae450)
		testing/testing.go:1058 +0x30d
	testing.tRunner.func1(0xc000502c00)
		testing/testing.go:1061 +0x41a
	panic(0x26c1720, 0x3aae450)
		runtime/panic.go:969 +0x175
	github.com/tendermint/iavl.(*ImmutableTree).Has(...)
		github.com/tendermint/iavl@v0.13.3/immutable_tree.go:122
	gitlab.com/vocdoni/go-dvote/vochain.(*State).EnvelopeExists(0xc000dd2540, 0x29bfb51, 0x3, 0x29bfad0, 0x3, 0x0)
		dvote/vochain/iavl.go:555 +0x206
	[...]

Fixes #262.