vochain/indexer: add a test that restores an older backup
This allows us to test our SQL migrations with real data from staging.
In particular, we need to now write a migration that moves data
from two columns, to be deleted, to one new column.
That is non-trivial enough to need a test.

Running the test on the PR changing the existing migrations
in a backwards-incompatible way breaks the test, as expected:

    --- FAIL: TestRestoreBackupAndMigrate (0.04s)
        migrations_test.go:46:
            error:
              got non-nil error
            got:
              e"error preparing query CreateProcess: table processes has no column named manually_ended"
            stack:
              /home/mvdan/src/voc/vochain/indexer/migrations_test.go:46
                qt.Assert(t, err, qt.IsNil)

The sqlite backup file is about 17MiB, but just under 5MiB with
zstd -15, which seems reasonable enough for a git testdata file.
We could trim it down, but we also want all that real data to test with.