data/ipfs: protect retrieveCache with a mutex
simplelru.LRU is not safe for concurrent use, and its use of maps
started catching that with runtime panics:

    fatal error: concurrent map writes

We do expect concurrent access, since concurrent API calls
can call ipfs.Handler.Retrieve, which then uses retrieveCache.

Put the cache behind a mutex. Given that the ratio of reads and writes
isn't known or likely to be heavily skewed towards reads,
it seems premature to try using the more complex sync.RWMutex.

It's unclear why this started happening now; the only recent change
to the LRU mechanism is the switch to the library's v2 with generics.
It is possible that the race was always there, but the old version
might not have been using maps as much, which caught the race.

Fixes #940.