vochain/indexer: do not use many connections with sqlite
The added comments explain the reasoning.
See https://github.com/mattn/go-sqlite3/issues/1022#issuecomment-1067353980.

Running the added regression before and after shows a clear difference:

	$ go test -v -run Concurrent
	=== RUN   TestIndexerConcurrentDB
		indexer_test.go:1022: iteration 116: database is locked
		indexer_test.go:1022: iteration 99: database is locked
		indexer_test.go:1022: iteration 108: database is locked
		indexer_test.go:1022: iteration 223: database is locked
		indexer_test.go:1022: iteration 114: database is locked
		indexer_test.go:1022: iteration 26: database is locked
		indexer_test.go:1022: iteration 299: database is locked
		indexer_test.go:1022: iteration 217: database is locked
	--- FAIL: TestIndexerConcurrentDB (6.05s)
	$ go test -v -run Concurrent
	=== RUN   TestIndexerConcurrentDB
	--- PASS: TestIndexerConcurrentDB (0.41s)

Fixes #642.